### ISSUE TITLE
Issue with building the peptoid 13AC1-6-A

### ISSUE THREAD

**Issue by starwingc** [starwingc/peptoid_24summer#4]
Hi, @vvoelz , the resulting peptoid looks wield, can you have a look? 

The peptoid path is:
`peptoid_24summer/peptoid/13AC1-6-A/neutral`

You can check the leap.log for detailed information

the PDB file looks like this:

![image](https://github.com/starwingc/peptoid_24summer/assets/152640562/41549130-4697-45bf-90c1-7c0e9e82998e)

**Comment by vvoelz** [comment]
Hi @starwingc -- the reason this looks weird is because `tleap` knows how to stitch the backbone together and that's it -- it won't rotate any bonds to avoid clashes. Minimization usually fixes this, but there's always the chance that rings get linked (looks like the case here!)

You can fix this by hand in Chimera or ChimeraX. I recommend:
1. loading in the *.gro file resulting from the acpype step
2. rotating torsions to fix clashes (Chimera makes guesses as to which atoms are bonded -- you'll probably have to delete some bonds and add others before rotation)
3. Save the result as a `*.pdb` (Chimera won't save as `*.gro`)
4. Use `gmx editconf` to convert the `*.pdb` to a `*.gro`


Here's a picture of a first step -- I had to add the amide bond between residue 1 and 2, delete a fake bond, and rotate the side chain of residue 2 out of the way.

<img width="1283" alt="image" src="https://github.com/starwingc/peptoid_24summer/assets/123431/4bbfa482-1a94-499a-8e89-57a2a4c7fa3a">

**Comment by starwingc** [comment]
I build them again and they looks fine now.
